INSERT INTO public.ranking_movies (id, movie_name) VALUES
                                                (1, 'Whispers of Destiny'),
                                                (2, 'Midnight Mirage'),
                                                (3, 'Eternal Echoes'),
                                                (4, 'Spectral Serenity'),
                                                (5, 'Rogue Reverie'),
                                                (6, 'Chronicles of Lumina'),
                                                (7, 'Shadows of Stardust'),
                                                (8, 'Silent Symphony'),
                                                (9, 'Enigma Enclave'),
                                                (10, 'Starlight Sonata'),
                                                (11, 'Infinite Illusion'),
                                                (12, 'Mystic Mosaic'),
                                                (13, 'Celestial Cipher'),
                                                (14, 'Labyrinth of Legends'),
                                                (15, 'Secrets of Solitude'),
                                                (16, 'Phantom Paradox'),
                                                (17, 'Whirlwind Whispers'),
                                                (18, 'Echoes of Eternity'),
                                                (19, 'Quantum Quandary'),
                                                (20, 'Whispering Willow'),
                                                (21, 'Lost in Luminosity'),
                                                (22, 'Emerald Elysium'),
                                                (23, 'Stellar Saga'),
                                                (24, 'Vortex Vision'),
                                                (25, 'Obsidian Odyssey'),
                                                (26, 'Moonlit Mirage'),
                                                (27, 'Astro Amplitude'),
                                                (28, 'Aurora Ascension'),
                                                (29, 'Serendipity Spell');